### ISSUE TITLE
Prepare report about BLS MSM precompiles performance

### ISSUE THREAD

**Issue by chfast** [ethereum/evmone#1041]
```[tasklist]
### Tasks
- [x] Check if using scalar 0xFFFFFF... is slower than random scalars
- [x] Load CSV benchmark data to spreadsheet
- [x] Try plotting error bars
- [x] Load data from geth/gnark
```

**Comment by chfast** [comment]
## Scalar 0xFFFF

The max scalar affects g1mul (it is slower than random) but not the g1msm. Moreover, it looks msm is worst-case all the time because g1mul(0xffff) matches msm of single input.

**Comment by chfast** [comment]
https://ethereum-magicians.org/t/eip-2537-bls12-precompile-discussion-thread/4187/81?u=chfast
