### ISSUE TITLE
Add Huff/EVM implementation of blake2bf precompile

### ISSUE THREAD

**Issue by chfast** [ethereum/evmone#766]
```[tasklist]
### Tasks
- [ ] Get the old blake2b Huff source code. One copy is available in https://github.com/ewasm/benchmarking/blob/master/evm/input_data/evmcode/blake2b_huff.huff. Maybe there are any newer. You can ask @zac-williamson (the author).
- [ ] Try to compile it with the newest Huff compiler. Fix it if needed.
- [ ] The original code executes whole blake2b hash function. The precompile has been changed and it only exposes the internal "compress" function. Check the spec of the [EIP-152](https://eips.ethereum.org/EIPS/eip-152).
- [ ] Update the Huff source code according to the spec.
- [ ] Add some unit tests if possible.
```
