### ISSUE TITLE
CI: Add clang-17

### ISSUE THREAD

**Issue by chfast** [ethereum/evmone#767]
```[tasklist]
### Tasks
- [x] Create `cpp-build-env` docker images with clang-17
- [ ] Upgrade CI config to use clang-17 as the latest clang
- [ ] Update clang-tidy config
```
