### ISSUE TITLE
Bytecode DSL

### ISSUE THREAD

**Issue by chfast** [ethereum/evmone#772]
Enhance the `bytecode` utility (from [bytecode.hpp](https://github.com/ethereum/evmone/blob/master/test/utils/bytecode.hpp).

```[tasklist]
### Tasks
- [ ] Rethink syntax (see below)
- [ ] Use S-expressions?
- [ ] Add support for jump labels
- [ ] Add support for user-defined macros
- [ ] Add support for user-defined functions
```

#### Concatenation (current)

```cpp
mstore(0, add(mload(0), 1)) + revert(0, msize());
```

#### Dot

```cpp
mstore(0, add(mload(0), 1)).revert(0, msize());
```

#### Inheritance
```cpp
{
    mstore(0, add(mload(0), 1));
    revert(0, msize());
}
```

#### Aggregate initialization
```cpp
bytecode{
    mstore(0, add(mload(0), 1)),
    revert(0, msize()),
};
```

**Comment by chfast** [comment]
Some inspirations:

- x86 assembly in C++ templates: https://github.com/mattbierner/Template-Assembly
- the C++ "overloaded lambdas" pattern: https://stackoverflow.com/questions/48661148/c17-inheriting-set-of-lambdas-with-template-argument-deduction-guides
- macro-free unit testing: https://github.com/boost-ext/ut
